### ISSUE TITLE
actions for exporting .nextjs

### ISSUE THREAD

**Issue by rubelux** [artizen-fund/artizen-frontend#29]
```
name: Debloy to AWS EBS for Staging
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Zip file
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'release.zip'
          path: '/.next'
      - name: Init Eb
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'init lab --region us-east-1 --platform node.js-16'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: Deploy to AWS Elastic Beanstalk
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'deploy Lab-env'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'

```
